# Generated by Django 4.0.6 on 2022-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pix',
            field=models.ImageField(default='dashboard/avatar.png', upload_to='dashboard'),
        ),
    ]
