# Generated by Django 4.0.6 on 2022-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shopcart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='cart_code',
            field=models.CharField(default='a', max_length=255),
        ),
    ]
